const WAD = 1e18;
const HALF_WAD = 1e9;
const OPTIMAL_UTILIZATION_RATE = 0.8 * 1e18;
const EXCESS_UTILIZATION_RATE = 0.2 * 1e18;

module.exports = {
  WAD,
  HALF_WAD,
  OPTIMAL_UTILIZATION_RATE,
  EXCESS_UTILIZATION_RATE,
};
